### ISSUE TITLE
Move the TitleBar as a separate layout file

### ISSUE THREAD

**Issue by rahul-sundaresan** [charlotte-urbanists/charlotte-urbanists#1]

**Comment by MThabsheer7** [comment]
Hey @rahul-sundaresan, I can work on this if you are willing to accept outside contributions.

**Comment by rahul-sundaresan** [comment]
Thank you for reaching out! I didn't realize this would be visible to everyone. At this point, I still need to update the repo with build instructions and rules. So it'll be a while before I can accept contributions and I refactored it myself

**Comment by MThabsheer7** [comment]
Okay cool @rahul-sundaresan
